### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by ZhaoShaw** [HHTpy/HHTpywrapper#7]
Hello there,
I encountered another difficulty. I used to run the EEMD function and everything worked. Today when I run again, I get an UnicodeDecodeError. I know it's a decoding problem, but I can't solve the error. Can you help me?

Here is my error：

ipdb> > d:\workplace\408\hht_sup.py(29)Hht_sup_ret()
     27 def Hht_sup_ret(xs):
     28     '''decomposition to imfs .matlab'''
62-> 29     eemd_post_processing=EEMD(xs,0.01, 50, num_imf=10, seed_no=1, post_processing=True)
63   30     eemd_post_processing.get_oi()
     31 

Starting MATLAB on ZMQ socket tcp://127.0.0.1:53735
Send 'exit' command to kill the server
......MATLAB started and connected!

ipdb> Traceback (most recent call last):

  File "<ipython-input-2-2dabd72fb639>", line 1, in <module>
    debugfile('D:/Workplace/408/Hht_sup.py', wdir='D:/Workplace/408')

  File "D:\Anaconda\envs\tensorflow\lib\site-packages\spyder\utils\site\sitecustomize.py", line 733, in debugfile
    debugger.run("runfile(%r, args=%r, wdir=%r)" % (filename, args, wdir))

  File "D:\Anaconda\envs\tensorflow\lib\bdb.py", line 431, in run
    exec(cmd, globals, locals)

  File "<string>", line 1, in <module>

  File "D:\Anaconda\envs\tensorflow\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "D:\Anaconda\envs\tensorflow\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "d:/workplace/408/hht_sup.py", line 44, in <module>
    Sup_io(table,K,time_long)

  File "d:/workplace/408/hht_sup.py", line 24, in Sup_io
    X_temp=Hht_sup_ret(X.loc[i*time_long:(i+1)*time_long-1,['spindle_torque']].values)

  File "d:/workplace/408/hht_sup.py", line 29, in Hht_sup_ret
    eemd_post_processing=EEMD(xs,0.01, 50, num_imf=10, seed_no=1, post_processing=True)

  File "D:\Anaconda\envs\tensorflow\Lib\site-packages\HHTpywrapper\hhtpywrapper\eemd.py", line 10, in __init__
    self.mlab = matlab.start_mlab()

  File "D:\Anaconda\envs\tensorflow\Lib\site-packages\HHTpywrapper\hhtpywrapper\matlab.py", line 12, in start_mlab
    res = mlab.run_func('addpath', dir_path + d)

  File "D:\Anaconda\envs\tensorflow\lib\site-packages\pymatbridge\pymatbridge.py", line 309, in run_func
    nargout=nargout)

  File "D:\Anaconda\envs\tensorflow\lib\site-packages\pymatbridge\pymatbridge.py", line 272, in _json_response
    return json.loads(self._response(**kwargs), object_hook=decode_pymat)

  File "D:\Anaconda\envs\tensorflow\lib\site-packages\pymatbridge\pymatbridge.py", line 230, in _response
    resp = self.socket.recv_string()

  File "D:\Anaconda\envs\tensorflow\lib\site-packages\zmq\sugar\socket.py", line 458, in recv_string
    return self._deserialize(msg, lambda buf: buf.decode(encoding))

  File "D:\Anaconda\envs\tensorflow\lib\site-packages\zmq\sugar\socket.py", line 419, in _deserialize
    return load(recvd)

  File "D:\Anaconda\envs\tensorflow\lib\site-packages\zmq\sugar\socket.py", line 458, in <lambda>
    return self._deserialize(msg, lambda buf: buf.decode(encoding))

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa8 in position 42: invalid start byte

**Comment by ZhaoShaw** [comment]
I am sorry!
I previously added a function for the marginal spectrum in the hsa method and added an empty path to the startup path, which caused this problem!
